# Source: https://www.nginx.com/blog/nginx-plus-ingress-controller-kubernetes-load-balancing/#tls
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secret
  # Kubernetes Namespaces can be used to divide a cluster into logical partitions allowing a single large Kubernetes cluster to be used by multiple users and teams, or a single user with multiple applications.
  # So we use the default namespace
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key