# Ideas here: https://stackoverflow.com/questions/60343474/how-to-get-secret-environment-variables-implemented-by-kubernetes-into-python
# secretGenerator:
#  - name: mysql-pass
#    literals:
#    - password=bX6eC9cH5qG1cE5dP3mA7fZ8cM8pN3eO
#  - name: mysql-user
#    literals:
#    - username=wpmt_cluster_db_user
#  - name: mysql-root-pass
#    literals:
#      - root-password=bX6eC9cH5qG1cE5dP3mA7fZ8cM8pN3eO
#resources:
#  - mysql-deployment.yaml