apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpmt-cluser-mysql-claim # This is used in the MySQL Deployment below when declaring the volumes
spec:
  # Source: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode
  volumeMode: Filesystem
  accessModes:
    # Source: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    # the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi