apiVersion: v1
kind: Service
metadata:
  name: wpmt-clusterip-log
spec:
  type: ClusterIP
  selector:
    app: wpmt-cluster-log-deployment
  ports:
  # This is the port on the container that can be accessed by other Pods/Containers
  - port: 6902
  # This is the port within the Pod that we want to provide access to  
    targetPort: 6902
